PF_X                        =    0x1  # Executable
PF_W                        =    0x2  # Writable
PF_R                        =    0x4  # Readable

O_RDONLY                = 0x00000000
O_WRONLY                = 0x00000001
O_RDWR                  = 0x00000002
O_CREAT                 = 0x00000040
O_EXCL                  = 0x00000080
O_NOCTTY                = 0x00000100
O_TRUNC                 = 0x00000200
O_APPEND                = 0x00000400
O_NONBLOCK              = 0x00000800
O_DIRECTORY             = 0x00004000
O_NOFOLLOW              = 0x00008000  # ARM/ARM64
O_CLOEXEC               = 0x00080000
O_PATH                  = 0x00200000  # ARM/ARM64

CLOCK_REALTIME              =    0
CLOCK_MONOTONIC             =    1
CLOCK_PROCESS_CPUTIME_ID    =    2
CLOCK_THREAD_CPUTIME_ID     =    3
CLOCK_MONOTONIC_RAW         =    4
CLOCK_REALTIME_COARSE       =    5
CLOCK_MONOTONIC_COARSE      =    6
CLOCK_BOOTTIME              =    7
CLOCK_REALTIME_ALARM        =    8
CLOCK_BOOTTIME_ALARM        =    9

FUTEX_WAIT                  =    0
FUTEX_WAKE                  =    1
FUTEX_FD                    =    2
FUTEX_REQUEUE               =    3
FUTEX_CMP_REQUEUE           =    4
FUTEX_WAKE_OP               =    5
FUTEX_LOCK_PI               =    6
FUTEX_UNLOCK_PI             =    7
FUTEX_TRYLOCK_PI            =    8
FUTEX_WAIT_BITSET           =    9
FUTEX_WAKE_BITSET           =    10
FUTEX_WAIT_REQUEUE_PI       =    11
FUTEX_CMP_REQUEUE_PI        =    12

FUTEX_PRIVATE_FLAG          =    128
FUTEX_CLOCK_REALTIME        =    256

FUTEX_CMD_MASK              =    ~(FUTEX_PRIVATE_FLAG | FUTEX_CLOCK_REALTIME)

#fcntl
#/* command values */
F_DUPFD                     =    0  #/* duplicate file descriptor */
F_GETFD                     =    1  #/* get file descriptor flags */
F_SETFD                     =    2  #/* set file descriptor flags */
F_GETFL                     =    3  #/* get file status flags */
F_SETFL                     =    4  #/* set file status flags */
F_GETOWN                    =    5  #/* get SIGIO/SIGURG proc/pgrp */
F_SETOWN                    =    6  #/* set SIGIO/SIGURG proc/pgrp */
F_GETLK                     =    7  #/* get record locking information */
F_SETLK                     =    8  #/* set record locking information */
F_SETLKW                    =    9  #/* F_SETLK; wait if blocked */

#/* file descriptor flags (F_GETFD, F_SETFD) */
FD_CLOEXEC                  =    1		#/* close-on-exec flag */

#/* record locking flags (F_GETLK, F_SETLK, F_SETLKW) */
F_RDLCK                     =    1		#/* shared or read lock */
F_UNLCK                     =    2		#/* unlock */
F_WRLCK                     =    3		#/* exclusive or write lock */
F_WAIT                      =    0x010  #/* Wait until lock is granted */
F_FLOCK                     =    0x020	#/* Use flock(2) semantics for lock */
F_POSIX                     =    0x040	#/* Use POSIX semantics for lock */


#dirfd
AT_FDCWD                    =    -100
AT_EMPTY_PATH               =    0x1000
AT_SYMLINK_NOFOLLOW         =    0x100

AT_NULL                     =    0
AT_IGNORE                   =    1
AT_EXECFD                   =    2
AT_PHDR                     =    3
AT_PHENT                    =    4
AT_PHNUM                    =    5
AT_PAGESZ                   =    6
AT_BASE                     =    7
AT_FLAGS                    =    8
AT_ENTRY                    =    9
AT_NOTELF                   =    10
AT_UID                      =    11
AT_EUID                     =    12
AT_GID                      =    13
AT_EGID                     =    14
AT_PLATFORM                 =    15
AT_HWCAP                    =    16
AT_CLKTCK                   =    17
AT_SECURE                   =    23
AT_BASE_PLATFORM            =    24
AT_RANDOM                   =    25
AT_HWCAP2                   =    26
AT_EXECFN                   =    31

DT_UNKNOWN                  =    0
DT_FIFO                     =    1
DT_CHR                      =    2
DT_DIR                      =    4
DT_BLK                      =    6
DT_REG                      =    8
DT_LNK                      =    10
DT_SOCK                     =    12

EPERM                     = 1     # /* Operation not permitted */
ENOENT                    = 2     # /* No such file or directory */
ESRCH                     = 3     # /* No such process */
EINTR                     = 4     # /* Interrupted system call */
EIO                       = 5     # /* Input/output error */
ENXIO                     = 6     # /* No such device or address */
E2BIG                     = 7     # /* Argument list too long */
ENOEXEC                   = 8     # /* Exec format error */
EBADF                     = 9     # /* Bad file descriptor */
ECHILD                    = 10    # /* No child processes */
EAGAIN                    = 11    # /* Resource temporarily unavailable */
ENOMEM                    = 12    # /* Cannot allocate memory */
EACCES                    = 13    # /* Permission denied */
EFAULT                    = 14    # /* Bad address */
ENOTBLK                   = 15    # /* Block device required */
EBUSY                     = 16    # /* Device or resource busy */
EEXIST                    = 17    # /* File exists */
EXDEV                     = 18    # /* Invalid cross-device link */
ENODEV                    = 19    # /* No such device */
ENOTDIR                   = 20    # /* Not a directory */
EISDIR                    = 21    # /* Is a directory */
EINVAL                    = 22    # /* Invalid argument */
ENFILE                    = 23    # /* Too many open files in system */
EMFILE                    = 24    # /* Too many open files */
ENOTTY                    = 25    # /* Inappropriate ioctl for device */
ETXTBSY                   = 26    # /* Text file busy */
EFBIG                     = 27    # /* File too large */
ENOSPC                    = 28    # /* No space left on device */
ESPIPE                    = 29    # /* Illegal seek */
EROFS                     = 30    # /* Read-only file system */
EMLINK                    = 31    # /* Too many links */
EPIPE                     = 32    # /* Broken pipe */
EDOM                      = 33    # /* Numerical argument out of domain */
ERANGE                    = 34    # /* Numerical result out of range */
EDEADLOCK                 = 35    # /* Resource deadlock avoided */
ENAMETOOLONG              = 36    # /* File name too long */
ENOLCK                    = 37    # /* No locks available */
ENOSYS                    = 38    # /* Function not implemented */
ENOTEMPTY                 = 39    # /* Directory not empty */
ELOOP                     = 40    # /* Too many levels of symbolic links */
ENOMSG                    = 42    # /* No message of desired type */
EIDRM                     = 43    # /* Identifier removed */
ECHRNG                    = 44    # /* Channel number out of range */
EL2NSYNC                  = 45    # /* Level 2 not synchronized */
EL3HLT                    = 46    # /* Level 3 halted */
EL3RST                    = 47    # /* Level 3 reset */
ELNRNG                    = 48    # /* Link number out of range */
EUNATCH                   = 49    # /* Protocol driver not attached */
ENOCSI                    = 50    # /* No CSI structure available */
EL2HLT                    = 51    # /* Level 2 halted */
EBADE                     = 52    # /* Invalid exchange */
EBADR                     = 53    # /* Invalid request descriptor */
EXFULL                    = 54    # /* Exchange full */
ENOANO                    = 55    # /* No anode */
EBADRQC                   = 56    # /* Invalid request code */
EBADSLT                   = 57    # /* Invalid slot */
EBFONT                    = 59    # /* Bad font file format */
ENOSTR                    = 60    # /* Device not a stream */
ENODATA                   = 61    # /* No data available */
ETIME                     = 62    # /* Timer expired */
ENOSR                     = 63    # /* Out of streams resources */
ENONET                    = 64    # /* Machine is not on the network */
ENOPKG                    = 65    # /* Package not installed */
EREMOTE                   = 66    # /* Object is remote */
ENOLINK                   = 67    # /* Link has been severed */
EADV                      = 68    # /* Advertise error */
ESRMNT                    = 69    # /* Srmount error */
ECOMM                     = 70    # /* Communication error on send */
EPROTO                    = 71    # /* Protocol error */
EMULTIHOP                 = 72    # /* Multihop attempted */
EDOTDOT                   = 73    # /* RFS specific error */
EBADMSG                   = 74    # /* Bad message */
EOVERFLOW                 = 75    # /* Value too large for defined data type */
ENOTUNIQ                  = 76    # /* Name not unique on network */
EBADFD                    = 77    # /* File descriptor in bad state */
EREMCHG                   = 78    # /* Remote address changed */
ELIBACC                   = 79    # /* Can not access a needed shared library */
ELIBBAD                   = 80    # /* Accessing a corrupted shared library */
ELIBSCN                   = 81    # /* .lib section in a.out corrupted */
ELIBMAX                   = 82    # /* Attempting to link in too many shared libraries */
ELIBEXEC                  = 83    # /* Cannot exec a shared library directly */
EILSEQ                    = 84    # /* Invalid or incomplete multibyte or wide character */
ERESTART                  = 85    # /* Interrupted system call should be restarted */
ESTRPIPE                  = 86    # /* Streams pipe error */
EUSERS                    = 87    # /* Too many users */
ENOTSOCK                  = 88    # /* Socket operation on non-socket */
EDESTADDRREQ              = 89    # /* Destination address required */
EMSGSIZE                  = 90    # /* Message too long */
EPROTOTYPE                = 91    # /* Protocol wrong type for socket */
ENOPROTOOPT               = 92    # /* Protocol not available */
EPROTONOSUPPORT           = 93    # /* Protocol not supported */
ESOCKTNOSUPPORT           = 94    # /* Socket type not supported */
ENOTSUP                   = 95    # /* Operation not supported */
EPFNOSUPPORT              = 96    # /* Protocol family not supported */
EAFNOSUPPORT              = 97    # /* Address family not supported by protocol */
EADDRINUSE                = 98    # /* Address already in use */
EADDRNOTAVAIL             = 99    # /* Cannot assign requested address */
ENETDOWN                  = 100   # /* Network is down */
ENETUNREACH               = 101   # /* Network is unreachable */
ENETRESET                 = 102   # /* Network dropped connection on reset */
ECONNABORTED              = 103   # /* Software caused connection abort */
ECONNRESET                = 104   # /* Connection reset by peer */
ENOBUFS                   = 105   # /* No buffer space available */
EISCONN                   = 106   # /* Transport endpoint is already connected */
ENOTCONN                  = 107   # /* Transport endpoint is not connected */
ESHUTDOWN                 = 108   # /* Cannot send after transport endpoint shutdown */
ETOOMANYREFS              = 109   # /* Too many references: cannot splice */
ETIMEDOUT                 = 110   # /* Connection timed out */
ECONNREFUSED              = 111   # /* Connection refused */
EHOSTDOWN                 = 112   # /* Host is down */
EHOSTUNREACH              = 113   # /* No route to host */
EALREADY                  = 114   # /* Operation already in progress */
EINPROGRESS               = 115   # /* Operation now in progress */
ESTALE                    = 116   # /* Stale file handle */
EUCLEAN                   = 117   # /* Structure needs cleaning */
ENOTNAM                   = 118   # /* Not a XENIX named type file */
ENAVAIL                   = 119   # /* No XENIX semaphores available */
EISNAM                    = 120   # /* Is a named type file */
EREMOTEIO                 = 121   # /* Remote I/O error */
EDQUOT                    = 122   # /* Disk quota exceeded */
ENOMEDIUM                 = 123   # /* No medium found */
EMEDIUMTYPE               = 124   # /* Wrong medium type */
ECANCELED                 = 125   # /* Operation canceled */
ENOKEY                    = 126   # /* Required key not available */
EKEYEXPIRED               = 127   # /* Key has expired */
EKEYREVOKED               = 128   # /* Key has been revoked */
EKEYREJECTED              = 129   # /* Key was rejected by service */
EOWNERDEAD                = 130   # /* Owner died */
ENOTRECOVERABLE           = 131   # /* State not recoverable */
ERFKILL                   = 132   # /* Operation not possible due to RF-kill */

PTRACE_TRACEME                  =   0x0
PTRACE_DETACH                   =   0x11